### ISSUE TITLE
Скачивание с remanga.org с помощью парсера

### ISSUE THREAD

**Issue by evgenii-moriakhin** [Otaku-Melons/remanga#6]
Привет
Ищу возможность скачать мангу с remanga.org, наткнулся на эту утилиту

Вопрос такой, я вижу, что это парсер метаданных манги с сайта. Не вижу функционала скачивания манги, но нашел возможность скачать обложки\изображения.
Т.е гипотетически, можно спарсить метаданные, достать оттуда урлы изображений и скачать их

Есть ли какой то алгоритм правильных действий/скриптов/готовый набор команд, для моей цели скачать мангу?
Или нужно самому писать обвязку над текущем парсером?

И в целом, этот функционал может выглядеть как новая фича к парсеру, так что данный issue можно рассматривать как фича-реквест

**Comment by DUB1401** [comment]
Данный парсер работает в связке с корпоративным проприетарным ПО, которое может выполнять загрузку файлов, однако я по понятным причинам не могу им поделиться.

Загрузка слайдов и создание *.CBR / *.CBZ архивов на данный момент не поддерживается, но она точно есть в планах на ближайшее время. Вы можете подписаться на обновления репозитория, а также я уведомлю вас о выпуске соответствующего обновления, закрыв этот пост.

**Comment by DUB1401** [comment]
Обработчик для сборки глав написан, но ещё не включён в стабильный выпуск. Вы можете использовать команду `build`, загрузив скрипт из ветки [main](https://github.com/DUB1401/RemangaParser/tree/main). Документация уже доступна. Порядок использования:

1. Выполнить парсинг тайтла при помощи команды `parse`.
2. Запустить сборку при помощи команды `build`.
3. Результат сборки будет помещён в директорию _Output_.

Помните, что широкое тестирование данного функционала не проводилось и в нём могут встречаться ошибки. Буду благодарен за найденные баги.

Если вам понравился проект, поддержите его звездой.
